name: Node.js CI

on:
  push:
    branches:
    - main
    - release/*
 pull_request:
    branches:
    - main

on:
  schedule:
  - cron: "0 2 * * 1-5"

on:
  workflow_dispatch:

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-latest
steps:
  - name: Setup Node
    uses: actions/setup-node@v4
    with:
      node-version: '20.x'
  - name: Install Dependencies
    run: npm install
  - name: npm build and test
    run: 
        npm run build --if-present
        npm test
